// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSyH2geWiO2RFoefRJ5AH-MTyqG0hRBuo',
    appId: '1:871313757635:web:309fe31206911fd7881976',
    messagingSenderId: '871313757635',
    projectId: 'kyptronixcare',
    authDomain: 'kyptronixcare.firebaseapp.com',
    storageBucket: 'kyptronixcare.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNuIHgBLjzZPCCTMzOICJLHF8F47i5HeM',
    appId: '1:871313757635:android:1ee4fd66b0d06de0881976',
    messagingSenderId: '871313757635',
    projectId: 'kyptronixcare',
    storageBucket: 'kyptronixcare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmmibSqy76I-4VJCAJazsTcv6sXN4DUwc',
    appId: '1:871313757635:ios:caa424fd56817b59881976',
    messagingSenderId: '871313757635',
    projectId: 'kyptronixcare',
    storageBucket: 'kyptronixcare.appspot.com',
    iosBundleId: 'com.kyptronix.kyptronixcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmmibSqy76I-4VJCAJazsTcv6sXN4DUwc',
    appId: '1:871313757635:ios:caa424fd56817b59881976',
    messagingSenderId: '871313757635',
    projectId: 'kyptronixcare',
    storageBucket: 'kyptronixcare.appspot.com',
    iosBundleId: 'com.kyptronix.kyptronixcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSyH2geWiO2RFoefRJ5AH-MTyqG0hRBuo',
    appId: '1:871313757635:web:31c41181fda5ed4c881976',
    messagingSenderId: '871313757635',
    projectId: 'kyptronixcare',
    authDomain: 'kyptronixcare.firebaseapp.com',
    storageBucket: 'kyptronixcare.appspot.com',
  );
}
